[package]
name = "ccaguest"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/veraison/ccaguest"
readme = "README.md"
description = "CLI for RATS-based attestation workflows for ARM CCA"
license = "Apache-2.0"
keywords = ["attestation", "verification", "veraison", "endorsements"]
categories = ["command-line-utilities", "cryptography", "security"]

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
clap-verbosity-flag = "3.0.4"
env_logger = "0.11.11"
log = "0.4.34"
thiserror = "2.0.20"
url = { version = "2.5.8", features = ["serde"] }
base64 = "0.23.1"
serde_json = "1.0.151"
regl = { git = "https://github.com/veraison/rust-regl.git", rev = "ce3293"}
rand = "0.10.2"
hex = "0.4.3"
tokio = "1.53.1"
coserv-rs = { git = "https://github.com/veraison/coserv-rs.git", features = ["openssl"], rev = "15121e8" }
veraison-apiclient = { git = "https://github.com/veraison/rust-apiclient.git", features = [ "disk-caching" ], rev = "3f43ee8" }
cover = { git = "https://github.com/veraison/cover.git", rev = "030bc2d" }
serde = "1.0.229"
ear = { git = "https://github.com/veraison/rust-ear", rev = "15184e9a" }

[dev-dependencies]
wiremock = "0.6.5"
tempfile = "3.27.0"